//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITventory_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices
    {
        public int dev_id { get; set; }
        public string dev_GAno { get; set; }
        public Nullable<int> dev_SilesiaNo { get; set; }
        public string dev_Nazwa { get; set; }
        public string dev_model { get; set; }
        public string dev_sn { get; set; }
        public string dev_pn { get; set; }
        public string dev_dataZakupu { get; set; }
        public string dev_nrFaktury { get; set; }
    
        public virtual Dostawca Dostawca { get; set; }
        public virtual kompTyp kompTyp { get; set; }
        public virtual Producent Producent { get; set; }
        public virtual Status Status { get; set; }
        public virtual Uzytkownicy Uzytkownicy { get; set; }
    }
}
