//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITventory_v2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITventoryEntities : DbContext
    {
        public ITventoryEntities()
            : base("name=ITventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dostawca> Dostawca { get; set; }
        public virtual DbSet<kompTyp> kompTyp { get; set; }
        public virtual DbSet<Komputery> Komputery { get; set; }
        public virtual DbSet<Producent> Producent { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Uzytkownicy> Uzytkownicy { get; set; }
    }
}
