//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITventory_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komputery
    {
        public int komp_id { get; set; }
        public string komp_GAno { get; set; }
        public Nullable<int> komp_SilesiaNo { get; set; }
        public string komp_Nazwa { get; set; }
        public Nullable<int> komp_status { get; set; }
        public Nullable<int> komp_uzyt { get; set; }
        public Nullable<int> komp_typ { get; set; }
        public Nullable<int> komp_producent { get; set; }
        public string komp_model { get; set; }
        public string komp_sn { get; set; }
        public string komp_pn { get; set; }
        public string komp_dataZakupu { get; set; }
        public Nullable<int> komp_dostawca { get; set; }
        public string komp_nrFaktury { get; set; }
    
        public virtual Dostawca Dostawca { get; set; }
        public virtual kompTyp kompTyp { get; set; }
        public virtual Producent Producent { get; set; }
        public virtual Status Status { get; set; }
        public virtual Uzytkownicy Uzytkownicy { get; set; }
    }
}
