//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITventory_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main
    {
        public int main_id { get; set; }
        public string main_GAno { get; set; }
        public Nullable<int> main_SilesiaNo { get; set; }
        public Nullable<int> main_namId { get; set; }
    
        public virtual Name Name { get; set; }
    }
}
